#!/usr/bin/env python

import sys
import word_model
import nonword_generator

text = open(sys.argv[1])
model = word_model.WordModel(text)
generator = nonword_generator.Generator(model)

print ''.join(generator.generate())
